import { describe, it, expect } from 'vitest';
import { fileURLToPath } from 'node:url';
import { existsSync, statSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import init from '../../dist/opencascade_single.js';
import packageJson from '../../package.json' with { type: 'json' };

/**
 * Validates the `exports` map in `package.json`.
 *
 * The contract:
 *   - `libcascade`         → ESM entry + types
 *   - `libcascade/wasm`    → opencascade_single.wasm (canonical
 *                                        locateFile target for every bundler)
 *   - `libcascade/multi`   → multi-threaded ESM entry + types
 *   - `libcascade/multi/wasm` → opencascade_multi.wasm
 *   - `libcascade/api-reference.json` → deterministic build-time API feed
 *   - `libcascade/package.json` → readable for tooling
 *
 * The subpath export is what lets consumers write
 *   `import wasmUrl from 'libcascade/wasm?url'`
 * across Vite, Bun, Node, and Deno without reaching into `dist/...` directly.
 *
 * If any of these contracts break, every starter template and doc snippet
 * that targets the v3 surface stops working — guard them with hard
 * assertions on the static `package.json` shape so test runs catch
 * accidental drift without needing the wasm artifact present.
 */
describe('package exports — wasm subpath contract', () => {
  it('should stay dependency-free', () => {
    expect('dependencies' in packageJson).toBe(false);
  });

  it('should declare ./wasm in the exports map pointing at the shipped wasm', () => {
    const exportsMap = packageJson.exports as Record<string, unknown>;
    expect(exportsMap, 'package.json must declare an exports field').toBeDefined();
    const wasmTarget = exportsMap['./wasm'];
    expect(
      wasmTarget,
      'package.json#exports must include a "./wasm" subpath so consumers can write `import wasmUrl from \'libcascade/wasm?url\'`',
    ).toBe('./dist/opencascade_single.wasm');
  });

  it('should declare the package root with both types and default conditions', () => {
    const exportsMap = packageJson.exports as Record<string, { types?: string; default?: string }>;
    const root = exportsMap['.'];
    expect(root, 'exports must declare the package root under "."').toBeDefined();
    // W3 assemble: the root is the eager entry (capability-selected, already
    // initialised, named value exports); the raw single-threaded factory
    // moved to `./single` and the shared d.ts replaced the per-variant ones.
    expect(root!.types).toBe('./dist/index.d.ts');
    expect(root!.default).toBe('./dist/index.js');
    const single = exportsMap['./single'];
    expect(single, 'exports must keep the raw single factory at "./single"').toBeDefined();
    expect(single!.default).toBe('./dist/opencascade_single.js');
    const init = exportsMap['./init'];
    expect(init, 'exports must declare the createInstance entry at "./init"').toBeDefined();
    expect(init!.default).toBe('./dist/init.js');
  });

  it('should expose ./package.json so tooling (npm explore, manifests) can read the manifest', () => {
    const exportsMap = packageJson.exports as Record<string, unknown>;
    expect(exportsMap['./package.json']).toBe('./package.json');
  });

  it('should expose the packaged API-reference feed', () => {
    const exportsMap = packageJson.exports as Record<string, unknown>;
    const files = packageJson.files as readonly string[];
    expect(exportsMap['./api-reference.json']).toBe('./dist/api-reference.json');
    expect(files).toContain('dist/api-reference.json');
    expect(basename(fileURLToPath(import.meta.resolve('libcascade/api-reference.json'))))
      .toBe('api-reference.json');
  });

  it('should include the wasm file in the published files allowlist', () => {
    const files = packageJson.files as readonly string[];
    expect(files).toContain('dist/opencascade_single.wasm');
  });

  it('should declare ./multi in the exports map with types and default conditions', () => {
    const exportsMap = packageJson.exports as Record<string, { types?: string; default?: string }>;
    const multi = exportsMap['./multi'];
    expect(multi, 'package.json#exports must include a "./multi" subpath').toBeDefined();
    // Shared-variant surface: both `./multi` and `./single` type against the
    // one variant.d.ts generated by `libcascade assemble`.
    expect(multi!.types).toBe('./dist/variant.d.ts');
    expect(multi!.default).toBe('./dist/opencascade_multi.js');
  });

  it('should declare ./multi/wasm in the exports map pointing at the MT wasm', () => {
    const exportsMap = packageJson.exports as Record<string, unknown>;
    expect(exportsMap['./multi/wasm']).toBe('./dist/opencascade_multi.wasm');
  });

  it('should include the MT artifacts in the published files allowlist', () => {
    const files = packageJson.files as readonly string[];
    expect(files).toContain('dist/opencascade_multi.wasm');
    expect(files).toContain('dist/opencascade_multi.js');
    // Per-variant d.ts no longer ships; the shared types.d.ts + variant.d.ts do.
    expect(files).toContain('dist/types.d.ts');
    expect(files).toContain('dist/variant.d.ts');
    expect(files).toContain('dist/opencascade_multi.provenance.json');
  });

  it('should resolve libcascade/multi to the MT loader the exports map declares', () => {
    const url = import.meta.resolve('libcascade/multi');
    expect(url.startsWith('file://'), `Expected file:// URL, got ${url}`).toBe(true);
    const resolvedPath = fileURLToPath(url);
    expect(basename(resolvedPath)).toBe('opencascade_multi.js');
    expect(dirname(resolvedPath).endsWith('/dist')).toBe(true);
  });

  it('should resolve libcascade/multi/wasm to the MT wasm the exports map declares', () => {
    const url = import.meta.resolve('libcascade/multi/wasm');
    const resolvedPath = fileURLToPath(url);
    expect(basename(resolvedPath)).toBe('opencascade_multi.wasm');
    expect(dirname(resolvedPath).endsWith('/dist')).toBe(true);
  });

  it('should resolve libcascade/wasm to the same file the exports map declares', async () => {
    // Self-reference resolution: a Node ESM package can import its own
    // subpath exports via `import.meta.resolve(name + subpath)`. This is
    // the same code path bundlers and downstream consumers exercise.
    const url = import.meta.resolve('libcascade/wasm');
    expect(url.startsWith('file://'), `Expected file:// URL, got ${url}`).toBe(true);
    const resolvedPath = fileURLToPath(url);
    expect(basename(resolvedPath)).toBe('opencascade_single.wasm');
    expect(dirname(resolvedPath).endsWith('/dist')).toBe(true);
  });

  it('should resolve libcascade/wasm to an existing file when the build artifact is present', () => {
    // Skip gracefully when the dist artifact has not been built yet — the
    // exports-map shape is already asserted above, so the wasm contract is
    // fully covered without requiring a 27 MB binary at test time.
    const url = import.meta.resolve('libcascade/wasm');
    const resolvedPath = fileURLToPath(url);
    const distWasm = join(dirname(resolvedPath), basename(resolvedPath));
    if (!existsSync(distWasm)) {
      return;
    }
    expect(statSync(distWasm).size).toBeGreaterThan(1_000_000);
  });

  it('should boot an OCCT instance via the canonical /wasm-subpath locateFile pattern (full round-trip)', async () => {
    // The runnable equivalent of the docs snippet:
    //   const WASM_DIR = dirname(fileURLToPath(import.meta.resolve('libcascade/wasm')));
    //   await init({ locateFile: (f) => join(WASM_DIR, f) });
    // If this passes, every doc/snippet that follows the same pattern works
    // end-to-end against the package's `exports` map.
    const wasmUrl = import.meta.resolve('libcascade/wasm');
    const wasmPath = fileURLToPath(wasmUrl);
    if (!existsSync(wasmPath)) return;
    const WASM_DIR = dirname(wasmPath);

    const oc = await init({ locateFile: (file: string) => join(WASM_DIR, file) });
    expect(oc).toBeDefined();
    expect(typeof oc.BRepPrimAPI_MakeBox).toBe('function');
    using box = new oc.BRepPrimAPI_MakeBox(10, 10, 10);
    using shape = box.Shape();
    expect(shape.IsNull()).toBe(false);
  }, 30_000);
});
