"""Handle-aware substituted-typedef peel resolver strategy.

The member-typedef peel successfully resolves NCollection accessors for
**plain** element types (typed-ids like ``BRepGraph_OccurrenceId``, simple
classes like ``BOPDS_Curve``), but **Handle-wrapped** element types
(``opencascade::handle<X>``) still collapse to ``unknown`` because the
resolver pipeline produces a substituted string (e.g.
``"opencascade::handle<TDF_Attribute>"``) that the canonical fallback in
:func:`resolveWithCanonicalFallback` cannot recognise — the string contains
``<`` so it fails the simple-name export check, and the qualified-member
walker doesn't peel handle wrappers.

This strategy closes the gap by *string-level* matching of the substituted
spelling against the three syntactic Handle wrapper shapes OCCT emits:

* ``opencascade::handle<X>`` — fully-qualified namespaced form, the shape
  that NCollection discovery emits for ``using``-declarations (all 247
  handle-wrapped instantiations in ``build/ncollection-manifest.json``
  use this exact form).
* ``occ::handle<X>`` — alternative namespace alias that OCCT V8 uses in
  some headers (e.g. ``GeomLProp_SLPropsBase<occ::handle<Geom_Surface>>``).
* ``Handle_X`` — the typedef form generated by ``DEFINE_STANDARD_HANDLE``
  and frequently used in OCCT API signatures.

For each shape, the strategy extracts the inner class name ``X``, consults
:meth:`_is_known_export_name`, and returns ``X`` when the inner type is
an emitted TypeScript export. This is the same contract
:func:`resolve_handle_recursive` enforces at the AST level — applied one
layer downstream, where the AST has been replaced by a substituted string.

Architectural notes:

* This strategy is *string-level*, not AST-level. It accepts a Python
  ``str`` rather than a ``clang.cindex.Type``. The signature departs
  from sibling strategies' ``(ctx, clang_type, ...)`` because there is no
  AST left to inspect after :func:`getTypedefedTemplateTypeAsString`
  substitutes the template argument.
* The regex is anchored (``^…$``) and tolerates outer ``const`` plus
  trailing ``&`` / ``*`` so it correctly handles
  ``"const opencascade::handle<X> &"`` and
  ``"const Handle_X *"`` shapes produced by reference- and
  pointer-returning accessors.
* No diagnostics-sink call: when the strategy declines (returns ``None``)
  the caller's existing canonical fallback runs and records the failure in
  ``build/any-type-report.json``. Adding a separate ``_collect_any``
  call here would double-count.
* Idempotent and pure: the strategy has no side effects beyond a single
  ``ctx._is_known_export_name`` lookup. Safe to call from every
  template-args substitution path.
"""

from __future__ import annotations

import re

# Anchored regex matching the three Handle wrapper shapes documented above.
# Tolerates outer ``const`` and trailing ``&`` / ``*`` so reference-returning
# accessors (``const_reference = const TheItemType &``) and pointer-returning
# accessors are both peeled.
#
# Capture groups:
#   ``ocname`` — inner type X from ``opencascade::handle<X>`` / ``occ::handle<X>``
#   ``hdname`` — inner type X from ``Handle_X`` typedef form
#
# Exactly one of the two named groups is populated per match.
_HANDLE_SUBSTITUTED_RE = re.compile(
    r"^\s*(?:const\s+)?"
    r"(?:"
    r"(?:opencascade|occ)::handle<(?P<ocname>[A-Za-z_]\w*)>"
    r"|"
    r"Handle_(?P<hdname>[A-Za-z_]\w*)"
    r")"
    r"\s*[&*]?\s*$"
)


def resolve_handle_substituted_typedef(
    ctx, substituted_spelling: str
) -> str | None:
    """Peel a substituted Handle wrapper at the string level.

    Called from :func:`resolveWithCanonicalFallback` after
    :func:`getTypedefedTemplateTypeAsString` replaces ``TheItemType`` with the
    substitution value's spelling. When that spelling matches
    ``opencascade::handle<X>`` / ``occ::handle<X>`` / ``Handle_X``, return
    ``X`` if it is a known TypeScript export. Returns ``None`` otherwise so
    the existing canonical-fallback path runs and the diagnostics report
    records the failure.

    Parameters
    ----------
    ctx
        The :class:`ResolverContext` (live ``TypescriptBindings`` instance).
        Only ``ctx._is_known_export_name`` is consulted.
    substituted_spelling
        The post-substitution type spelling. May contain ``const`` qualifier
        and trailing ``&`` / ``*``; the regex strips them transparently.

    Returns
    -------
    Optional[str]
        The inner class name when the wrapper matches and the inner class is
        a known export; ``None`` in every other case (empty input, no
        regex match, inner class not in exports).
    """
    if not substituted_spelling:
        return None

    match = _HANDLE_SUBSTITUTED_RE.match(substituted_spelling)
    if not match:
        return None

    inner = match.group("ocname") or match.group("hdname")
    if not inner:
        return None

    if ctx._is_known_export_name(inner):
        return inner
    return None
