/**
 * Auto-generated by ``scripts/generate-sub2b-regression-pins.py``.
 * Sub-2b regression pin for ``Geom2dConvert_CompCurveToBSplineCurve`` (module TKGeomBase).
 *
 * Policy: matrix row 8 (degenerate sibling constructors) /
 *         rule 2 (sibling-aliasing detection) /
 *         rule 6 (no dispatcher precedence inversion).
 * See ``repos/opencascade.js/docs/policy/ocjs-trailing-default-emission-policy.md``.
 *
 * Background: before Phase 1's bindgen-side sibling-aliasing detector,
 * libembind's optional-wildcard short-circuit (Hunk 3) would silently
 * shadow the larger-arity constructor of this class whenever a caller
 * invoked the larger ctor with the smaller ctor's discriminator value.
 * Phase 1 introduced the rule-2 detector at the bindgen level; Phase 3
 * routes the conflict pair through ``val_default.emit_method_with_val_default``
 * at the larger arity; Phase 4 (big-bang regeneration) is what flips this
 * pin green by producing the val-discriminated single constructor.
 *
 * Pre-Phase-4 verdict: FAILS or constructs both via the smaller-ctor
 * branch (val-default classifier is wired in Phase 3 but the published
 * WASM artefact is pre-Phase-3 today). Some pins additionally fail at
 * argument coercion because the placeholder identifiers ("face",
 * "vector", "multiLine", "fn", "dataHandle", "curve1", "curve2",
 * "boundedCurve", "cellCount", "theTolX", "theTolF") cannot be
 * fabricated without OCCT context; the goal of the pin is to FAIL
 * loudly at the dispatch level once Phase 4 ships and these placeholders
 * are replaced with real fixtures.
 *
 * Post-Phase-4 verdict: PASSES — the smaller and larger ctor produce
 * distinguishable instances, and the val-discrimination lambda routes
 * arity-(N+1) calls to the larger ctor regardless of trailing-default
 * coercion.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { initOC, getOC, wasmExists } from '../../smoke/helpers.js';

const SKIP_REASON = '';

describe.skipIf(!wasmExists)(
  'Sub-2b regression pin: Geom2dConvert_CompCurveToBSplineCurve (TKGeomBase)',
  () => {
    beforeAll(async () => {
      await initOC();
    });

    const runner = SKIP_REASON ? it.skip : it;
    runner(
      `smaller-ctor and larger-ctor calls land on distinct dispatch branches${SKIP_REASON ? ` — SKIPPED: ${SKIP_REASON}` : ''}`,
      () => {
        const oc = getOC();
        // Typed class accessor — the sub-2b conflict pair is constructed via
        // `Reflect.construct` so the placeholder/spread argument lists (several
        // of which are intentionally arity- or type-mismatched pre-Phase-4) do
        // not require a type-suppression cast. The dispatch outcome — distinct
        // instances per ctor branch — is what the pin measures.
        const Cls = oc.Geom2dConvert_CompCurveToBSplineCurve;
        expect(typeof Cls).toBe('function');
        using boundedCurvePnt = new oc.gp_Pnt2d(0, 0);
        using boundedCurveDir = new oc.gp_Dir2d(1, 0);
        using boundedCurveLine = new oc.Geom2d_Line(boundedCurvePnt, boundedCurveDir);
        using boundedCurve = new oc.Geom2d_TrimmedCurve(boundedCurveLine, 0, 1);
        using smaller = Reflect.construct(Cls, [undefined]);
        using larger = Reflect.construct(Cls, [boundedCurve, undefined]);
        expect(smaller).toBeDefined();
        expect(larger).toBeDefined();
        expect(smaller).not.toBe(larger);
      },
    );
  },
);
