/**
 * Auto-generated by ``scripts/generate-sub2b-regression-pins.py``.
 * Verifies that ``Geom2dAPI_InterCurveCurve`` resolves overlapping smaller- and
 * larger-arity constructor calls to distinct dispatch branches.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { initOC, getOC, wasmExists } from '../../smoke/helpers.js';

const SKIP_REASON = '';

describe.skipIf(!wasmExists)(
  'Sub-2b regression pin: Geom2dAPI_InterCurveCurve (TKGeomAlgo)',
  () => {
    beforeAll(async () => {
      await initOC();
    });

    const runner = SKIP_REASON ? it.skip : it;
    runner(
      `smaller-ctor and larger-ctor calls land on distinct dispatch branches${SKIP_REASON ? ` — SKIPPED: ${SKIP_REASON}` : ''}`,
      () => {
        const oc = getOC();
        // Typed class accessor — the sub-2b conflict pair is constructed via
        // `Reflect.construct` so the placeholder/spread argument lists (several
        // of which are intentionally arity- or type-mismatched pre-Phase-4) do
        // not require a type-suppression cast. The dispatch outcome — distinct
        // instances per ctor branch — is what the pin measures.
        const Cls = oc.Geom2dAPI_InterCurveCurve;
        expect(typeof Cls).toBe('function');
        using curve1Pnt = new oc.gp_Pnt2d(0, 0);
        using curve1Dir = new oc.gp_Dir2d(1, 0);
        using curve1 = new oc.Geom2d_Line(curve1Pnt, curve1Dir);
        using curve2Pnt = new oc.gp_Pnt2d(0, 0);
        using curve2Dir = new oc.gp_Dir2d(0, 1);
        using curve2 = new oc.Geom2d_Line(curve2Pnt, curve2Dir);
        using smaller = Reflect.construct(Cls, [curve1, undefined]);
        using larger = Reflect.construct(Cls, [curve1, curve2, undefined]);
        expect(smaller).toBeDefined();
        expect(larger).toBeDefined();
        expect(smaller).not.toBe(larger);
      },
    );
  },
);
