/**
 * Auto-generated by ``scripts/generate-sub2b-regression-pins.py``.
 * Verifies that ``GeomConvert_CompCurveToBSplineCurve`` resolves overlapping smaller- and
 * larger-arity constructor calls to distinct dispatch branches.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { initOC, getOC, wasmExists } from '../../smoke/helpers.js';

const SKIP_REASON = '';

describe.skipIf(!wasmExists)(
  'Sub-2b regression pin: GeomConvert_CompCurveToBSplineCurve (TKGeomBase)',
  () => {
    beforeAll(async () => {
      await initOC();
    });

    const runner = SKIP_REASON ? it.skip : it;
    runner(
      `smaller-ctor and larger-ctor calls land on distinct dispatch branches${SKIP_REASON ? ` — SKIPPED: ${SKIP_REASON}` : ''}`,
      () => {
        const oc = getOC();
        // Typed class accessor — the sub-2b conflict pair is constructed via
        // `Reflect.construct` so the placeholder/spread argument lists (several
        // of which are intentionally arity- or type-mismatched pre-Phase-4) do
        // not require a type-suppression cast. The dispatch outcome — distinct
        // instances per ctor branch — is what the pin measures.
        const Cls = oc.GeomConvert_CompCurveToBSplineCurve;
        expect(typeof Cls).toBe('function');
        using boundedCurvePnt = new oc.gp_Pnt2d(0, 0);
        using boundedCurveDir = new oc.gp_Dir2d(1, 0);
        using boundedCurveLine = new oc.Geom2d_Line(boundedCurvePnt, boundedCurveDir);
        using boundedCurve = new oc.Geom2d_TrimmedCurve(boundedCurveLine, 0, 1);
        using smaller = Reflect.construct(Cls, [undefined]);
        using larger = Reflect.construct(Cls, [boundedCurve, undefined]);
        expect(smaller).toBeDefined();
        expect(larger).toBeDefined();
        expect(smaller).not.toBe(larger);
      },
    );
  },
);
