/**
 * Auto-generated by ``scripts/generate-sub2b-regression-pins.py``.
 * Verifies that ``Approx_FitAndDivide`` resolves overlapping smaller- and
 * larger-arity constructor calls to distinct dispatch branches.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { initOC, getOC, wasmExists } from '../../smoke/helpers.js';

const SKIP_REASON = '';

describe.skipIf(!wasmExists)(
  'Sub-2b regression pin: Approx_FitAndDivide (TKGeomBase)',
  () => {
    beforeAll(async () => {
      await initOC();
    });

    const runner = SKIP_REASON ? it.skip : it;
    runner(
      `smaller-ctor and larger-ctor calls land on distinct dispatch branches${SKIP_REASON ? ` — SKIPPED: ${SKIP_REASON}` : ''}`,
      () => {
        const oc = getOC();
        // Typed class accessor — the sub-2b conflict pair is constructed via
        // `Reflect.construct` so the placeholder/spread argument lists (several
        // of which are intentionally arity- or type-mismatched pre-Phase-4) do
        // not require a type-suppression cast. The dispatch outcome — distinct
        // instances per ctor branch — is what the pin measures.
        const Cls = oc.Approx_FitAndDivide;
        expect(typeof Cls).toBe('function');
        using smaller = Reflect.construct(Cls, [undefined, undefined, undefined, undefined, undefined, undefined, undefined]);
        using larger = Reflect.construct(Cls, [undefined /* AppCont_Function placeholder — supply post-Phase-4 */, undefined, undefined, undefined, undefined, undefined, undefined, undefined]);
        expect(smaller).toBeDefined();
        expect(larger).toBeDefined();
        expect(smaller).not.toBe(larger);
      },
    );
  },
);
