/**
 * Auto-generated by ``scripts/generate-sub2b-regression-pins.py``.
 * Verifies that overlapping smaller- and larger-arity calls to
 * ``BRepGProp_Face`` return separate objects.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { initOC, getOC, wasmExists } from '../../smoke/helpers.js';

const SKIP_REASON = '';

describe.skipIf(!wasmExists)(
  'Sub-2b regression pin: BRepGProp_Face (TKTopAlgo)',
  () => {
    beforeAll(async () => {
      await initOC();
    });

    const runner = SKIP_REASON ? it.skip : it;
    runner(
      `smaller-ctor and larger-ctor calls return separate objects${SKIP_REASON ? ` — SKIPPED: ${SKIP_REASON}` : ''}`,
      () => {
        const oc = getOC();
        // Typed class accessor — the sub-2b conflict pair is constructed via
        // `Reflect.construct` so the placeholder/spread argument lists (several
        // of which are intentionally arity- or type-mismatched pre-Phase-4) do
        // not require a type-suppression cast. Successful construction and
        // distinct object identities are what the pin measures.
        const Cls = oc.BRepGProp_Face;
        expect(typeof Cls).toBe('function');
        using smaller = Reflect.construct(Cls, [true]);
        using larger = Reflect.construct(Cls, [undefined /* face placeholder — supply via TopExp_Explorer post-Phase-4 */, true]);
        expect(smaller).toBeDefined();
        expect(larger).toBeDefined();
        expect(smaller).not.toBe(larger);
      },
    );
  },
);
