/**
 * Parser for a per-variant `.d.ts` emitted by the container's `dts` step.
 *
 * The generated file has one fixed shape, so this reads anchors rather than
 * typechecking anything:
 *
 * ```text
 * <declarations>                        declare class / declare const / type / interface
 * export type { X };                    one line per exported name
 * export type OpenCascadeInstance = {   FS + wasmMemory prelude
 * } & {                                 one `Name: typeof Name;` per bound symbol
 * };
 * export type InitOpenCascadeOptions = { … };
 * export default function init(…);
 * ```
 *
 * `assemble` unions N of these into one shared `types.d.ts`, so every anchor is
 * asserted: a bindgen change that moves one fails here with the file named,
 * instead of silently producing a d.ts missing half its exports.
 */

/** The `export type { … }` block marks the end of the declarations. */
const EXPORT_BLOCK_ANCHOR = '\nexport type { ';
const INSTANCE_ANCHOR = '\nexport type OpenCascadeInstance = {';
const INSTANCE_INTERSECTION = '\n} & {\n';
const OPTIONS_ANCHOR = '\nexport type InitOpenCascadeOptions = {';

export type ParsedVariantDts = {
  /** Variant name this file was produced for. */
  readonly variant: string;
  /** Everything before the `export type { … }` block, verbatim. */
  readonly declarations: string;
  /** Names exported as types (superset of {@link valueSymbols} plus pure aliases). */
  readonly exportedNames: readonly string[];
  /** `Name: typeof Name` members of `OpenCascadeInstance` — the runtime values. */
  readonly valueSymbols: readonly string[];
  /** The `export type OpenCascadeInstance = { … } & {` prelude, verbatim. */
  readonly instancePrelude: string;
  /** The `export type InitOpenCascadeOptions = { … };` block, verbatim. */
  readonly optionsBlock: string;
};

const assertAnchor = (condition: boolean, message: string): void => {
  if (!condition) {
    throw new Error(
      `${message} The .d.ts is generated by the container's \`dts\` step; a bindgen change that ` +
        'moves this anchor needs a matching change in packages/toolchain/src/assemble/dts.ts.',
    );
  }
};

/**
 * Parse one variant `.d.ts`.
 *
 * @param variant - Variant name (used in error messages and exclusivity notes).
 * @param source - Full file contents.
 * @param filePath - Path printed in anchor-failure errors.
 * @returns The parsed sections.
 * @throws Error naming the missing anchor when the file shape is unexpected.
 */
export const parseVariantDts = (
  variant: string,
  source: string,
  filePath: string,
): ParsedVariantDts => {
  const exportBlockStart = source.indexOf(EXPORT_BLOCK_ANCHOR);
  assertAnchor(exportBlockStart !== -1, `${filePath} has no \`export type { … }\` block.`);

  const instanceStart = source.indexOf(INSTANCE_ANCHOR);
  assertAnchor(instanceStart !== -1, `${filePath} has no \`export type OpenCascadeInstance\`.`);

  const optionsStart = source.indexOf(OPTIONS_ANCHOR);
  assertAnchor(optionsStart !== -1, `${filePath} has no \`export type InitOpenCascadeOptions\`.`);

  const intersection = source.indexOf(INSTANCE_INTERSECTION, instanceStart);
  assertAnchor(
    intersection !== -1 && intersection < optionsStart,
    `${filePath}'s OpenCascadeInstance is not an \`{ … } & { … }\` intersection.`,
  );

  const instancePrelude = source.slice(instanceStart + 1, intersection + INSTANCE_INTERSECTION.length);
  const instanceMembers = source.slice(intersection + INSTANCE_INTERSECTION.length, optionsStart);
  const optionsEnd = source.indexOf('\n};', optionsStart);
  assertAnchor(optionsEnd !== -1, `${filePath}'s InitOpenCascadeOptions block is unterminated.`);

  const exportedNames = [...source.slice(exportBlockStart).matchAll(/^export type \{ (\w+) \};$/gm)].map(
    (match) => match[1] as string,
  );
  const valueSymbols = [...instanceMembers.matchAll(/^ {2}(\w+): typeof \1;$/gm)].map(
    (match) => match[1] as string,
  );

  assertAnchor(exportedNames.length > 0, `${filePath} exports no type names.`);
  assertAnchor(valueSymbols.length > 0, `${filePath}'s OpenCascadeInstance declares no bound symbols.`);

  return {
    variant,
    declarations: source.slice(0, exportBlockStart + 1),
    exportedNames,
    valueSymbols,
    instancePrelude,
    optionsBlock: source.slice(optionsStart + 1, optionsEnd + 3),
  };
};

/**
 * Split a declarations blob into top-level chunks keyed by declared name.
 *
 * The generated d.ts indents every nested line, so a column-0 line starting a
 * declaration (or the JSDoc immediately above one) always begins a new
 * top-level chunk. Only used when variants disagree — identical declaration
 * blobs are passed through verbatim, which is the single-config case.
 *
 * @param declarations - The declarations section of a parsed variant d.ts.
 * @returns Declared name → its chunk (leading JSDoc included).
 */
export const splitDeclarations = (declarations: string): Map<string, string> => {
  const starts = [...declarations.matchAll(/^(?:\/\*\*|declare |type |interface )/gm)].map(
    (match) => match.index,
  );
  const chunks = new Map<string, string>();
  let pending = '';

  for (const [index, start] of starts.entries()) {
    const chunk = pending + declarations.slice(start, starts[index + 1] ?? declarations.length);
    const name = /^(?:declare (?:class|const|function|enum|namespace)|type|interface) (\w+)/m.exec(
      chunk,
    )?.[1];
    if (name === undefined) {
      // A standalone JSDoc block: belongs to the declaration that follows it.
      pending = chunk;
      continue;
    }
    pending = '';
    chunks.set(name, (chunks.get(name) ?? '') + chunk);
  }

  return chunks;
};
