/**
 * Generate a package surface from built variant declarations and manifests.
 * Outputs shared types, init factories, the eager root, raw variant types, and
 * an exports fragment. {@link collectSymbols} supplies both JavaScript and
 * declaration renderers from one symbol list.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

import {
  type BuildConfig,
  type BuildVariant,
  variantCapabilities,
  variantOutputName,
} from '../config/index.ts';

import { type ParsedVariantDts, parseVariantDts, splitDeclarations } from './dts.ts';

/** Emitted file names, relative to the dist directory. */
export const ASSEMBLE_OUTPUTS = {
  types: 'types.d.ts',
  init: 'init.js',
  initTypes: 'init.d.ts',
  root: 'index.js',
  rootTypes: 'index.d.ts',
  variantTypes: 'variant.d.ts',
  exports: 'exports.json',
} as const;

/** An `exports` map value: a string target or a conditions object. */
export type ExportsEntry = string | Record<string, string>;
export type ExportsMap = Record<string, ExportsEntry>;

export type AssembleOptions = {
  /** Validated config (supplies variants and output names). */
  readonly config: BuildConfig;
  /** Package root — the config's directory. */
  readonly configDirectory: string;
  /** Absolute path to the artifact directory. @defaultValue `<configDirectory>/dist` */
  readonly distDirectory?: string;
  /**
   * Package name, used for the `Symbol.for('<name>.select')` pre-import
   * override. @defaultValue the `name` in `<configDirectory>/package.json`
   */
  readonly packageName?: string;
};

export type AssembleResult = {
  /** Absolute paths written. */
  readonly written: readonly string[];
  /** The `exports` fragment (package-root-relative targets). */
  readonly exports: ExportsMap;
  /** Generated package `files` entries (package-root-relative). */
  readonly files: readonly string[];
  /** Symbols exported as runtime values by every variant. */
  readonly sharedSymbolCount: number;
  /** Symbol → the variants that bind it, for symbols not bound by all of them. */
  readonly exclusiveSymbols: ReadonlyMap<string, readonly string[]>;
};

const GENERATED_BANNER = (source: string): string =>
  `// Generated by \`libcascade assemble\` from ${source}. Do not edit.\n`;

/** Node-vs-browser probe used by the selector and the worker-path conversion. */
const IS_NODE_SNIPPET = `typeof process !== 'undefined' && typeof process.versions?.node === 'string'`;

const readJson = <T>(filePath: string): T => JSON.parse(fs.readFileSync(filePath, 'utf8')) as T;

/**
 * Read and parse each variant's `.d.ts`.
 *
 * @param config - The build configuration.
 * @param distDirectory - Directory `libcascade build` wrote artifacts into.
 * @returns One parse result per declared variant, in declaration order.
 * @throws Error naming the missing artifact and the command that produces it.
 */
export const readVariantDts = (
  config: BuildConfig,
  distDirectory: string,
): readonly ParsedVariantDts[] =>
  config.variants.map((variant) => {
    const outputName = variantOutputName(config, variant);
    const dtsPath = path.join(distDirectory, `${outputName}.d.ts`);
    if (!fs.existsSync(dtsPath)) {
      throw new Error(
        `Missing ${dtsPath} for variant "${variant.name}". Run \`libcascade build --variant ` +
          `${variant.name}\` first — assemble only packages artifacts, it never builds them.`,
      );
    }
    return parseVariantDts(variant.name, fs.readFileSync(dtsPath, 'utf8'), dtsPath);
  });

export type CollectedSymbols = {
  /** Runtime value exports, base-variant order first, then variant-exclusive additions. */
  readonly values: readonly string[];
  /** Names exported as types only (aliases with no runtime binding). */
  readonly types: readonly string[];
  /** Symbol → variants binding it, only for symbols some variant lacks. */
  readonly exclusive: ReadonlyMap<string, readonly string[]>;
};

/**
 * Union the parsed variant surfaces into one symbol list.
 *
 * @param parsed - Per-variant parse results, in declaration order.
 * @returns The shared value/type symbol lists plus the variant-exclusivity map.
 */
export const collectSymbols = (parsed: readonly ParsedVariantDts[]): CollectedSymbols => {
  const variantsBySymbol = new Map<string, string[]>();
  const values: string[] = [];
  const types: string[] = [];
  const seenValue = new Set<string>();
  const seenType = new Set<string>();

  for (const variant of parsed) {
    for (const symbol of variant.valueSymbols) {
      variantsBySymbol.set(symbol, [...(variantsBySymbol.get(symbol) ?? []), variant.variant]);
      if (!seenValue.has(symbol)) {
        seenValue.add(symbol);
        values.push(symbol);
      }
    }
  }
  for (const variant of parsed) {
    for (const name of variant.exportedNames) {
      if (seenValue.has(name) || seenType.has(name)) continue;
      seenType.add(name);
      types.push(name);
    }
  }

  const exclusive = new Map<string, readonly string[]>();
  for (const [symbol, variants] of variantsBySymbol) {
    if (variants.length !== parsed.length) exclusive.set(symbol, variants);
  }

  return { values, types, exclusive };
};

/**
 * Union the declaration blobs.
 *
 * Identical blobs (the usual case — the bindings list is shared across
 * variants) are passed through verbatim. Otherwise the longest blob is the base
 * and the declarations only other variants carry are appended.
 *
 * @param parsed - Per-variant parse results.
 * @returns One declarations blob covering every variant's symbols.
 */
export const unionDeclarations = (parsed: readonly ParsedVariantDts[]): string => {
  const base = [...parsed].sort((a, b) => b.declarations.length - a.declarations.length)[0];
  if (base === undefined) throw new Error('No variants to assemble.');
  if (parsed.every((variant) => variant.declarations === base.declarations)) return base.declarations;

  const declared = new Set(splitDeclarations(base.declarations).keys());
  const additions: string[] = [];
  for (const variant of parsed) {
    if (variant === base) continue;
    for (const [name, chunk] of splitDeclarations(variant.declarations)) {
      if (declared.has(name)) continue;
      declared.add(name);
      additions.push(`// Declared only by the "${variant.variant}" variant.\n${chunk}`);
    }
  }
  return `${base.declarations}\n${additions.join('')}`;
};

const renderNameList = (names: readonly string[]): string =>
  names.map((name) => `  ${name},`).join('\n');

/**
 * Render the shared `types.d.ts`.
 *
 * Value symbols are re-exported with `export { X }` over the existing
 * `declare class X` rather than rewritten to `export declare class X`: the two
 * are equivalent to consumers (`import { gp_Pnt } from 'libcascade'` binds a
 * real value either way) and this leaves the 11 MB declaration blob untouched.
 *
 * @param parsed - Per-variant parse results.
 * @param symbols - The unioned symbol lists.
 * @param variantNames - Declared variant names, for the `LibcascadeVariant` union.
 * @returns The file contents.
 */
export const renderSharedTypes = (
  parsed: readonly ParsedVariantDts[],
  symbols: CollectedSymbols,
  variantNames: readonly string[],
): string => {
  const base = parsed[0];
  if (base === undefined) throw new Error('No variants to assemble.');

  const members = symbols.values.map((symbol) => {
    const variants = symbols.exclusive.get(symbol);
    return variants === undefined
      ? `  ${symbol}: typeof ${symbol};`
      : `  /** Bound only by the ${variants.map((name) => `\`${name}\``).join(', ')} variant(s). */\n` +
          `  ${symbol}?: typeof ${symbol};`;
  });

  return [
    GENERATED_BANNER(parsed.map((variant) => `${variant.variant}.d.ts`).join(' + ')),
    '// One surface shared by every variant: the per-variant .d.ts files are not',
    '// published, so single and multi instances are structurally comparable.',
    '',
    unionDeclarations(parsed),
    'export {',
    renderNameList(symbols.values),
    '};',
    '',
    'export type {',
    renderNameList(symbols.types),
    '};',
    '',
    base.instancePrelude.trimEnd(),
    members.join('\n'),
    '};',
    '',
    base.optionsBlock,
    '',
    '/** A variant declared by this package\'s build configuration. */',
    `export type LibcascadeVariant = ${variantNames.map((name) => `'${name}'`).join(' | ')};`,
    '',
    '/** Options accepted by `createInstance` from the `./init` subpath. */',
    'export type CreateInstanceOptions = InitOpenCascadeOptions & {',
    '  /**',
    '   * Variant to load. Omitted, the most capable variant the host supports is',
    '   * selected (see the `./init` entry for the capability probes).',
    '   */',
    '  variant?: LibcascadeVariant;',
    '  /**',
    "   * Size of OCCT's default thread pool for a threads variant. Omitted, OCCT",
    '   * sizes the pool itself and the launch cap is raised to match it.',
    '   */',
    '  threadCount?: number;',
    '};',
    '',
  ].join('\n');
};

/** Per-variant packaging facts the generated entries need. */
type VariantAsset = {
  readonly name: string;
  readonly outputName: string;
  readonly requires: readonly string[];
  /** Whether the variant's build bound the OCCT thread-pool sizing symbols. */
  readonly hasThreadPool: boolean;
};

const THREAD_POOL_SYMBOLS = ['OSD_ThreadPool', 'ConfigureThreadPool'];

/**
 * Emitted probe per {@link VariantCapability}.
 *
 * Only the capabilities some variant actually needs reach the generated
 * `./init` entry, so a config whose variants differ on nothing ships no probes.
 * A variant's capabilities are `variantCapabilities()` — its explicit
 * `requires` unioned with what its build flags imply — not the `requires`
 * array alone, so a threaded variant is probed even when it declares nothing.
 */
const CAPABILITY_PROBES: Record<string, { readonly probe: string; readonly hint: string }> = {
  threads: {
    probe:
      '  threads: () =>\n' +
      "    typeof SharedArrayBuffer !== 'undefined' && (globalThis.crossOriginIsolated ?? IS_NODE),",
    hint:
      'Threads need SharedArrayBuffer, which browsers gate behind cross-origin isolation ' +
      '(Cross-Origin-Opener-Policy: same-origin + Cross-Origin-Embedder-Policy: require-corp).',
  },
};

/**
 * Fail rather than emit a probe-less capability that would silently make every
 * variant requiring it unloadable.
 *
 * @param capability - The unrecognised capability name.
 * @throws Error naming the capability and where probes are declared.
 */
const unknownCapability = (capability: string): never => {
  throw new Error(
    `No selector probe for the "${capability}" capability. Add one to CAPABILITY_PROBES in ` +
      'packages/toolchain/src/assemble/index.ts alongside the VariantCapability union.',
  );
};

/**
 * Collect the per-variant packaging facts from the build manifests.
 *
 * @param config - The build configuration.
 * @param distDirectory - Directory holding the manifests.
 * @returns One entry per declared variant, in declaration order.
 */
export const readVariantAssets = (
  config: BuildConfig,
  distDirectory: string,
): readonly VariantAsset[] =>
  config.variants.map((variant: BuildVariant) => {
    const outputName = variantOutputName(config, variant);
    const manifestPath = path.join(distDirectory, `${outputName}.build-manifest.json`);
    if (!fs.existsSync(manifestPath)) {
      throw new Error(
        `Missing ${manifestPath} for variant "${variant.name}". Run \`libcascade build --variant ` +
          `${variant.name}\` first.`,
      );
    }
    const manifest = readJson<{ symbols?: { requested?: readonly string[] } }>(manifestPath);
    const requested = new Set(manifest.symbols?.requested ?? []);
    return {
      name: variant.name,
      outputName,
      requires: variantCapabilities(config, variant),
      hasThreadPool: THREAD_POOL_SYMBOLS.some((symbol) => requested.has(symbol)),
    };
  });

/**
 * Make Emscripten 6 pthread glue spawn workers from the glue asset actually
 * loaded by the host. Bundlers may hash that asset, so its build-time file name
 * is no longer a valid sibling URL at runtime.
 */
const normalizeThreadedGlue = (
  assets: readonly VariantAsset[],
  distDirectory: string,
): readonly string[] =>
  assets.flatMap((asset) => {
    if (!asset.requires.includes('threads')) return [];

    const gluePath = path.join(distDirectory, `${asset.outputName}.js`);
    const source = fs.readFileSync(gluePath, 'utf8');
    const original = `new Worker(new URL("${asset.outputName}.js",import.meta.url),`;
    const normalized = 'new Worker(new URL(import.meta.url),';
    const originalCount = source.split(original).length - 1;
    const normalizedCount = source.split(normalized).length - 1;

    if (originalCount === 0 && normalizedCount === 1) return [];
    if (originalCount !== 1 || normalizedCount !== 0) {
      throw new Error(
        `Expected exactly one Emscripten pthread worker self-reference in ${gluePath}.`,
      );
    }

    fs.writeFileSync(gluePath, source.replace(original, normalized));
    return [gluePath];
  });

/**
 * File name of the glue-pinned entry for one variant — the `./<variant>/init`
 * subpath. Flat in `dist/`, so it keeps the same `./<glue>.js` relative
 * resolution (and the same `./runtime`-free module graph) as `init.js`.
 *
 * @param variant - Variant name.
 * @returns The dist-relative file name.
 */
export const variantInitFile = (variant: string): string => `init.${variant}.js`;

/** Declaration file for one glue-pinned entry. */
export const variantInitTypesFile = (variant: string): string => `init.${variant}.d.ts`;

/**
 * Doc paragraph explaining what a glue-pinned entry buys over `./init`.
 *
 * @param pinned - The single variant this entry resolves.
 * @returns JSDoc body lines, terminated by a ` *` separator line.
 */
const pinnedNote = (pinned: string): string =>
  ` * The \`./${pinned}/init\` subpath. It contains exactly one
 * \`new URL(<glue>, import.meta.url)\`, so a bundle that imports it carries no
 * other variant's glue JS. The shared \`./init\` must be able to reach every
 * variant, so it names every glue — and Vite's \`vite:asset-import-meta-url\`
 * transform emits an asset for each at transform time, before tree-shaking,
 * whichever one runtime selection ends up fetching. Prefer this entry when
 * bundle size matters more than automatic selection.
 *
`;

/**
 * Render an init entry: the `./init` selector, or a glue-pinned
 * `./<variant>/init`.
 *
 * The shared entry owns runtime selection. Pinned entries use a separate
 * renderer below so selector exports and overrides cannot leak into their API.
 *
 * @param assets - Per-variant packaging facts; one entry pins that variant.
 * @param packageName - Namespace for the `Symbol.for('<name>.select')` override.
 * @param pinned - Variant name when rendering a `./<variant>/init` entry.
 * @returns The file contents.
 */
export const renderInit = (
  assets: readonly VariantAsset[],
  packageName: string,
): string => {
  const anyThreadPool = assets.some((asset) => asset.hasThreadPool);
  const capabilities = [...new Set(assets.flatMap((asset) => asset.requires))].map((name) => ({
    name,
    ...(CAPABILITY_PROBES[name] ?? unknownCapability(name)),
  }));
  const glueCase = (body: (asset: VariantAsset) => string): string =>
    assets.map((asset) => `    case '${asset.name}':\n      return ${body(asset)};`).join('\n');

  return `${GENERATED_BANNER('libcascade.config.ts + the per-variant build manifests')}
/**
 * ${packageName} instance factory.
 *
 * Owns the plumbing every consumer otherwise reimplements: variant selection,
 * glue self-reference for pthread worker spawning, Node \`file:\` URL → path
 * conversion, and OCCT thread-pool sizing.
 */

const IS_NODE = ${IS_NODE_SNIPPET};

/**
 * Host capability probes. A variant is loadable only when every capability its
 * build \`requires\` probes true. Only the capabilities some declared variant
 * actually requires are emitted.
 */
const CAPABILITIES = {${capabilities.map((capability) => `\n${capability.probe}`).join('')}
};

/** Remediation printed when a requested variant's requirement is unmet. */
const CAPABILITY_HINTS = ${JSON.stringify(
    Object.fromEntries(capabilities.map((capability) => [capability.name, capability.hint])),
    undefined,
    2,
  )};

/** Declared variants, in configuration order. */
const VARIANTS = ${JSON.stringify(
    assets.map((asset) => ({ name: asset.name, requires: asset.requires })),
    undefined,
    2,
  )};

/** Pre-import override: \`globalThis[Symbol.for('${packageName}.select')] = '${assets.at(-1)?.name ?? ''}'\`. */
export const SELECT_OVERRIDE = Symbol.for('${packageName}.select');

const unsupported = (variant) =>
  variant.requires.filter((capability) => !(CAPABILITIES[capability]?.() ?? false));

/**
 * Pick the most capable variant this host supports.
 *
 * Ties are broken by configuration order; the override symbol wins outright.
 *
 * @returns The selected variant name.
 * @throws Error when no declared variant is loadable here.
 */
export const selectVariant = () => {
  const override = globalThis[SELECT_OVERRIDE];
  if (typeof override === 'string') return override;

  const eligible = VARIANTS.filter((variant) => unsupported(variant).length === 0);
  const best = eligible.reduce(
    (winner, variant) => (variant.requires.length > winner.requires.length ? variant : winner),
    eligible[0],
  );
  if (best === undefined) {
    throw new Error(
      \`No ${packageName} variant can run here. Declared variants and their unmet requirements: \` +
        VARIANTS.map((variant) => \`\${variant.name} (needs \${unsupported(variant).join(', ')})\`).join(
          '; ',
        ) +
        '.',
    );
  }
  return best.name;
};

const glueUrl = (variant) => {
  switch (variant) {
${glueCase((asset) => `new URL('./${asset.outputName}.js', import.meta.url).href`)}
  }
  return undefined;
};

/**
 * Load a variant's Emscripten glue from its own asset URL.
 *
 * The import is deliberately opaque to bundlers. A statically analysable
 * \`import('./<variant>.js')\` makes them follow the glue, and a pthread build
 * contains \`new Worker(new URL(<glue>, import.meta.url))\` — so the bundler
 * re-bundles the glue as a worker entry, which fails on Emscripten's Node
 * branches, and drags every variant (including a 20 MB+ .wasm) into apps that
 * only ever load one. The \`new URL(...)\` above still emits each glue as a
 * first-class asset; only the graph edge into it is cut.
 *
 * The glue resolves its .wasm relative to itself, so a bundled app must pass
 * \`locateFile\`, \`wasmBinary\`, or \`instantiateWasm\` (the \`./<variant>/wasm\`
 * export gives the binary's URL).
 */
const loadGlue = (variant) => {
  const href = glueUrl(variant);
  if (href === undefined) {
    throw new Error(
      \`Unknown variant "\${variant}". Declared: ${assets.map((asset) => asset.name).join(', ')}.\`,
    );
  }
  return import(/* webpackIgnore: true */ /* @vite-ignore */ href);
};

/**
 * Emscripten spawns pthread workers from the glue's own URL. Node's \`Worker\`
 * takes a path, and a \`file:\` URL's pathname keeps a leading slash before a
 * Windows drive letter that Node rejects.
 */
const workerScript = (variant) => {
  const href = glueUrl(variant);
  if (href === undefined || !IS_NODE || !href.startsWith('file:')) return href;
  const filePath = decodeURIComponent(new URL(href).pathname);
  return process.platform === 'win32' ? filePath.replace(/^\\/([A-Za-z]:)/, '$1') : filePath;
};
${
  anyThreadPool
    ? `
/**
 * Size OCCT's default pool and raise its launch cap to match, so the lazily
 * created default does not stay smaller than the pre-spawned worker count
 * baked into the binary.
 */
const configureThreadPool = (instance, threadCount) => {
  const pool = instance.OSD_ThreadPool?.DefaultPool?.(threadCount ?? -1);
  if (pool === undefined) return;
  pool.SetNbDefaultThreadsToLaunch(threadCount ?? pool.NbThreads());
};
`
    : ''
}
/**
 * Create a fully initialised ${packageName} instance.
 *
 * @param options - Variant selection plus the Emscripten module overrides.
 * @returns The initialised instance.
 * @throws Error when the requested variant is unknown or unsupported here.
 */
export const createInstance = async (options = {}) => {
  const { variant: requested, threadCount, ...moduleOptions } = options;
  const name = requested ?? selectVariant();
  const variant = VARIANTS.find((candidate) => candidate.name === name);
  if (variant === undefined) {
    throw new Error(
      \`Unknown variant "\${name}". Declared: ${assets.map((asset) => asset.name).join(', ')}.\`,
    );
  }

  const missing = unsupported(variant);
  if (missing.length > 0) {
    throw new Error(
      \`The "\${name}" variant requires \${missing.join(', ')}, which this host does not provide. \` +
        missing.map((capability) => CAPABILITY_HINTS[capability]).join(' ') +
        ' Provide the capability, or request a variant without the requirement.',
    );
  }

  const { default: factory } = await loadGlue(name);
  const instance = await factory({ mainScriptUrlOrBlob: workerScript(name), ...moduleOptions });
${
  anyThreadPool
    ? `  if (variant.requires.includes('threads')) configureThreadPool(instance, threadCount);\n`
    : ''
}  return instance;
};

export default createInstance;
`;
};

/** Render a factory whose import path fixes the only loadable variant. */
const renderPinnedInit = (asset: VariantAsset, packageName: string): string => {
  const capabilities = asset.requires.map((name) => ({
    name,
    ...(CAPABILITY_PROBES[name] ?? unknownCapability(name)),
  }));
  const supportsThreadPool = asset.requires.includes('threads') && asset.hasThreadPool;
  const threadPool = supportsThreadPool
    ? `
const configureThreadPool = (instance, threadCount) => {
  const pool = instance.OSD_ThreadPool?.DefaultPool?.(threadCount ?? -1);
  if (pool === undefined) return;
  pool.SetNbDefaultThreadsToLaunch(threadCount ?? pool.NbThreads());
};
`
    : '';

  return `${GENERATED_BANNER('libcascade.config.ts + the per-variant build manifests')}
/**
 * ${packageName} instance factory, pinned to the "${asset.name}" variant.
 *
${pinnedNote(asset.name)} * The import path is the variant selector. This module exports no runtime
 * selector and rejects a contradictory \`variant\` option before loading glue.
 */

const IS_NODE = ${IS_NODE_SNIPPET};
const CAPABILITIES = {${capabilities.map((capability) => `\n${capability.probe}`).join('')}
};
const CAPABILITY_HINTS = ${JSON.stringify(
    Object.fromEntries(capabilities.map((capability) => [capability.name, capability.hint])),
    undefined,
    2,
  )};
const VARIANT = ${JSON.stringify(
    { name: asset.name, requires: asset.requires },
    undefined,
    2,
  )};
const unsupported = () =>
  VARIANT.requires.filter((capability) => !(CAPABILITIES[capability]?.() ?? false));
const glueUrl = () => new URL('./${asset.outputName}.js', import.meta.url).href;

const loadGlue = () =>
  import(/* webpackIgnore: true */ /* @vite-ignore */ glueUrl());

const workerScript = () => {
  const href = glueUrl();
  if (!IS_NODE || !href.startsWith('file:')) return href;
  const filePath = decodeURIComponent(new URL(href).pathname);
  return process.platform === 'win32' ? filePath.replace(/^\\/([A-Za-z]:)/, '$1') : filePath;
};
${threadPool}
/** Create a fully initialised "${asset.name}" instance. */
export const createInstance = async (options = {}) => {
  if (Object.hasOwn(options, 'variant')) {
    throw new Error(
      'The "${asset.name}" variant is fixed by the "./${asset.name}/init" import; remove the variant option.',
    );
  }

  const missing = unsupported();
  if (missing.length > 0) {
    throw new Error(
      'The "${asset.name}" variant requires ' +
        missing.join(', ') +
        ', which this host does not provide. ' +
        missing.map((capability) => CAPABILITY_HINTS[capability]).join(' '),
    );
  }

  const { threadCount, ...moduleOptions } = options;
  const { default: factory } = await loadGlue();
  const instance = await factory({ mainScriptUrlOrBlob: workerScript(), ...moduleOptions });
${supportsThreadPool ? '  configureThreadPool(instance, threadCount);\n' : ''}  return instance;
};

export default createInstance;
`;
};

/**
 * Render the eager root: capability-probed init plus a named-export barrel.
 *
 * @param symbols - The unioned symbol lists (same input as the d.ts).
 * @param assets - Per-variant glue and WASM asset metadata.
 * @returns The file contents.
 */
export const renderEagerRoot = (
  symbols: CollectedSymbols,
  assets: readonly VariantAsset[],
): string =>
  [
    GENERATED_BANNER('the shared symbol list'),
    '// Eager root: selects a variant, initialises it with top-level await, and',
    '// re-exports every bound symbol as a named value. Import `./init` instead to',
    '// control when (and whether) the WASM module is instantiated.',
    "import { createInstance, selectVariant } from './init.js';",
    '',
    `const IS_NODE = ${IS_NODE_SNIPPET};`,
    'const variant = selectVariant();',
    'const wasmUrl = (() => {',
    '  switch (variant) {',
    ...assets.map(
      (asset) =>
        `    case '${asset.name}':\n      return new URL('./${asset.outputName}.wasm', import.meta.url).href;`,
    ),
    '    default:',
    "      throw new Error(`Unknown selected variant \"${variant}\".`);",
    '  }',
    '})();',
    "const wasmPath = !IS_NODE || !wasmUrl.startsWith('file:')",
    '  ? wasmUrl',
    '  : (() => {',
    '      const filePath = decodeURIComponent(new URL(wasmUrl).pathname);',
    "      return process.platform === 'win32' ? filePath.replace(/^\\/([A-Za-z]:)/, '$1') : filePath;",
    '    })();',
    'const oc = await createInstance({',
    '  variant,',
    "  locateFile: (file, prefix = '') => (file.endsWith('.wasm') ? wasmPath : `${prefix}${file}`),",
    '});',
    '',
    'export default oc;',
    ...symbols.values.map((symbol) =>
      symbols.exclusive.has(symbol)
        ? `export const ${symbol} = oc.${symbol}; // variant-exclusive: ${(symbols.exclusive.get(symbol) ?? []).join(', ')}`
        : `export const ${symbol} = oc.${symbol};`,
    ),
    '',
  ].join('\n');

/**
 * Re-export the whole shared surface as types.
 *
 * `types.d.ts` exports every bound symbol as a runtime *value* (the eager root
 * really does bind them). The lazy entries do not, so they re-export the
 * same names with `export type *`: `import { TopoDS_Shape } from '<pkg>'` keeps
 * working in type position — the surface the per-variant `export type { X }`
 * d.ts files gave before assemble unified them — without promising a value the
 * lazy entries never export.
 */
const TYPE_ONLY_REEXPORT = "export type * from './types.js';";

const renderInitTypes = (): string =>
  `${GENERATED_BANNER('the shared symbol list')}import type { CreateInstanceOptions, OpenCascadeInstance } from './types.js';

${TYPE_ONLY_REEXPORT}

/** Pre-import variant override key: \`globalThis[SELECT_OVERRIDE] = 'multi'\`. */
export declare const SELECT_OVERRIDE: symbol;

/** Most capable variant this host supports. */
export declare const selectVariant: () => string;

/** Create a fully initialised instance. */
export declare const createInstance: (
  options?: CreateInstanceOptions,
) => Promise<OpenCascadeInstance>;

export default createInstance;
`;

const renderPinnedInitTypes = (asset: VariantAsset): string => {
  const options = asset.requires.includes('threads')
    ? `InitOpenCascadeOptions & {
  /** Size of OCCT's default thread pool. */
  threadCount?: number;
}`
    : 'InitOpenCascadeOptions';

  return `${GENERATED_BANNER('the shared symbol list')}import type { InitOpenCascadeOptions, OpenCascadeInstance } from './types.js';

${TYPE_ONLY_REEXPORT}

/** Options accepted by this fixed-variant initializer. */
export type CreateInstanceOptions = ${options};

/** Create a fully initialised "${asset.name}" instance. */
export declare const createInstance: (
  options?: CreateInstanceOptions,
) => Promise<OpenCascadeInstance>;

export default createInstance;
`;
};

const renderEagerRootTypes = (): string =>
  `${GENERATED_BANNER('the shared symbol list')}import type { OpenCascadeInstance } from './types.js';

export * from './types.js';

/** The instance this entry initialised at import time. */
declare const oc: OpenCascadeInstance;
export default oc;
`;

const renderVariantTypes = (): string =>
  `${GENERATED_BANNER('the shared symbol list')}import type { InitOpenCascadeOptions, OpenCascadeInstance } from './types.js';

// The per-variant subpaths resolve to the raw Emscripten glue, whose only
// export is the module factory. Named symbol exports live on the root entry.
${TYPE_ONLY_REEXPORT}

declare const init: (options?: InitOpenCascadeOptions) => Promise<OpenCascadeInstance>;
export default init;
`;

/**
 * Build the `exports` fragment.
 *
 * `./<variant>/init` is emitted only for a multi-variant package: with one
 * variant the shared `./init` already resolves exactly one glue, so a pinned
 * entry would duplicate it. Multi-variant pinned entries receive exact
 * declarations that omit the shared selector and `variant` option.
 *
 * @param assets - Per-variant packaging facts.
 * @param distName - Dist directory name relative to the package root.
 * @returns Subpath → target, with package-root-relative paths.
 */
export const renderExports = (
  assets: readonly VariantAsset[],
  distName: string,
): ExportsMap => {
  const target = (file: string): string => `./${path.posix.join(distName, file)}`;
  const map: ExportsMap = {
    '.': { types: target(ASSEMBLE_OUTPUTS.rootTypes), default: target(ASSEMBLE_OUTPUTS.root) },
    './init': { types: target(ASSEMBLE_OUTPUTS.initTypes), default: target(ASSEMBLE_OUTPUTS.init) },
  };
  for (const asset of assets) {
    map[`./${asset.name}`] = {
      types: target(ASSEMBLE_OUTPUTS.variantTypes),
      default: target(`${asset.outputName}.js`),
    };
    if (assets.length > 1) {
      map[`./${asset.name}/init`] = {
        types: target(variantInitTypesFile(asset.name)),
        default: target(variantInitFile(asset.name)),
      };
    }
    map[`./${asset.name}/wasm`] = target(`${asset.outputName}.wasm`);
  }
  return map;
};

/**
 * Merge a generated fragment into an existing `exports` map.
 *
 * Generated subpaths win; every other existing subpath is preserved in place,
 * which is what keeps hand-declared aliases (`./wasm`, `./api-reference.json`,
 * `./package.json`) working.
 *
 * @param existing - The package's current `exports` map.
 * @param fragment - The generated fragment.
 * @returns The merged map: existing keys in their original order, then new ones.
 */
export const mergePackageExports = (
  existing: ExportsMap | undefined,
  fragment: ExportsMap,
): ExportsMap => {
  const merged: ExportsMap = {};
  for (const [subpath, entry] of Object.entries(existing ?? {})) {
    merged[subpath] = fragment[subpath] ?? entry;
  }
  for (const [subpath, entry] of Object.entries(fragment)) {
    merged[subpath] ??= entry;
  }
  return merged;
};

/** Whether a package `files` entry belongs to `libcascade assemble`. */
const isGeneratedPackageFile = (file: string, distName: string): boolean => {
  const normalized = file.replace(/^\.\//, '');
  const directory = distName.replace(/^\.\//, '').replace(/\/$/, '');
  const prefix = directory === '.' ? '' : `${directory}/`;
  if (!normalized.startsWith(prefix)) return false;
  const name = normalized.slice(prefix.length);
  return (
    Object.values(ASSEMBLE_OUTPUTS).includes(name as (typeof ASSEMBLE_OUTPUTS)[keyof typeof ASSEMBLE_OUTPUTS]) ||
    /^init\..+\.js$/.test(name) ||
    /(?:\.js|\.wasm|\.d\.ts)$/.test(name)
  );
};

/** Replace generated dist entries while preserving every hand-maintained file. */
export const mergePackageFiles = (
  existing: readonly string[] | undefined,
  generated: readonly string[],
  distName: string,
): string[] => {
  const merged: string[] = [];
  let inserted = false;
  for (const file of existing ?? []) {
    if (isGeneratedPackageFile(file, distName)) {
      if (!inserted) {
        merged.push(...generated);
        inserted = true;
      }
    } else {
      merged.push(file);
    }
  }
  if (!inserted) merged.push(...generated);
  return [...new Set(merged)];
};

/** Package files produced or consumed by one assemble run. */
const renderPackageFiles = (
  assets: readonly VariantAsset[],
  distName: string,
): string[] => {
  const target = (file: string): string => path.posix.join(distName, file);
  const outputs = [
    ASSEMBLE_OUTPUTS.types,
    ASSEMBLE_OUTPUTS.init,
    ASSEMBLE_OUTPUTS.initTypes,
    ASSEMBLE_OUTPUTS.variantTypes,
    ASSEMBLE_OUTPUTS.root,
    ASSEMBLE_OUTPUTS.rootTypes,
    ...(assets.length > 1
      ? assets.flatMap((asset) => [variantInitFile(asset.name), variantInitTypesFile(asset.name)])
      : []),
  ];
  const artifacts = assets.flatMap((asset) => [
    `${asset.outputName}.js`,
    `${asset.outputName}.wasm`,
  ]);
  return [...outputs, ...artifacts].map(target);
};

/**
 * Generate the packaging surface for a built config.
 *
 * @param options - Config, package root, and optional dist/package-name overrides.
 * @returns The written paths, the exports fragment, and symbol statistics.
 * @throws Error when a variant's build artifacts are missing.
 * @example
 * ```typescript
 * const { exports } = assemble({ config, configDirectory: process.cwd() });
 * ```
 */
export const assemble = (options: AssembleOptions): AssembleResult => {
  const { config, configDirectory } = options;
  const distDirectory = options.distDirectory ?? path.join(configDirectory, 'dist');
  const packageJsonPath = path.join(configDirectory, 'package.json');
  const packageName =
    options.packageName ??
    (fs.existsSync(packageJsonPath)
      ? readJson<{ name?: string }>(packageJsonPath).name
      : undefined) ??
    config.name;

  const parsed = readVariantDts(config, distDirectory);
  const assets = readVariantAssets(config, distDirectory);
  const normalizedGlue = normalizeThreadedGlue(assets, distDirectory);
  const symbols = collectSymbols(parsed);
  const files: Record<string, string> = {
    [ASSEMBLE_OUTPUTS.types]: renderSharedTypes(
      parsed,
      symbols,
      config.variants.map((variant) => variant.name),
    ),
    [ASSEMBLE_OUTPUTS.init]: renderInit(assets, packageName),
    [ASSEMBLE_OUTPUTS.initTypes]: renderInitTypes(),
    [ASSEMBLE_OUTPUTS.variantTypes]: renderVariantTypes(),
    [ASSEMBLE_OUTPUTS.root]: renderEagerRoot(symbols, assets),
    [ASSEMBLE_OUTPUTS.rootTypes]: renderEagerRootTypes(),
  };

  // One glue-pinned entry per variant, for consumers that know which variant
  // they want. Skipped at N=1, where `./init` is already exactly this file.
  if (assets.length > 1) {
    for (const asset of assets) {
      files[variantInitFile(asset.name)] = renderPinnedInit(asset, packageName);
      files[variantInitTypesFile(asset.name)] = renderPinnedInitTypes(asset);
    }
  }

  const distName = path.relative(configDirectory, distDirectory) || '.';
  const exportsMap = renderExports(assets, distName);
  const packageFiles = renderPackageFiles(assets, distName);
  files[ASSEMBLE_OUTPUTS.exports] = `${JSON.stringify({ exports: exportsMap }, undefined, 2)}\n`;

  fs.mkdirSync(distDirectory, { recursive: true });
  const generated = Object.entries(files).map(([name, contents]) => {
    const filePath = path.join(distDirectory, name);
    fs.writeFileSync(filePath, contents);
    return filePath;
  });
  const written = [...normalizedGlue, ...generated];

  return {
    written,
    exports: exportsMap,
    files: packageFiles,
    sharedSymbolCount: symbols.values.length - symbols.exclusive.size,
    exclusiveSymbols: symbols.exclusive,
  };
};

/**
 * Merge generated exports and package files into the package's package.json.
 *
 * @param configDirectory - Package root holding package.json.
 * @param fragment - The fragment returned by {@link assemble}.
 * @param files - Generated `files` entries returned by {@link assemble}.
 * @returns The absolute path written.
 */
export const writePackageExports = (
  configDirectory: string,
  fragment: ExportsMap,
  files: readonly string[],
): string => {
  const packageJsonPath = path.join(configDirectory, 'package.json');
  const packageJson = readJson<{ exports?: ExportsMap; files?: string[] }>(packageJsonPath);
  const mergedExports = mergePackageExports(packageJson.exports, fragment);
  const firstTarget = files[0];
  const distName = firstTarget === undefined ? 'dist' : path.posix.dirname(firstTarget);
  const mergedFiles = mergePackageFiles(packageJson.files, files, distName);
  fs.writeFileSync(
    packageJsonPath,
    `${JSON.stringify({ ...packageJson, exports: mergedExports, files: mergedFiles }, undefined, 2)}\n`,
  );
  return packageJsonPath;
};
